sudo: required 
language: node_js
node_js:
    - "stable"
    
services: 
    - docker

jobs:
  include:
    - stage: build and test
      script:     
      - docker build -t garimasingh2018/hackerapp -f Dockerfile .
      - docker run -e CI=true garimasingh2018/hackerapp npm run test -- --coverage
    - stage: publish image
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      - docker push garimasingh2018/hackerapp:"$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER" ;
