sudo: required 
language: node_js
node_js:
    - "stable"
    
services: 
    - docker

before_install: 
    - docker build -t garimasingh2018/hackerapp -f Dockerfile .
script:     
    - docker run -e CI=true garimasingh2018/hackerapp npm run test 
after_success:
   - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 
   - docker push garimasingh2018/hackerapp:"$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER" 
   - docker logout
